version: "3.9"

services:
  api:
    image: "rpi-api:v1"
    restart: unless-stopped

    command: sh -c "poetry run python /api/rpi_api.py"

    #Debug tty connection
    #stdin_open: true
    #tty: true

    build:
      context: ./api

    networks:
      - api-nginx-net

    environment:
      - APP_CONFIG=${APP_CONFIG}
      - API_URL_PREFIX=${API_URL_PREFIX}
      - DHT_PIN=${DHT_PIN}
      - SOIL_MOISTURE_PIN=${SOIL_MOISTURE_PIN}
      - SOIL_MOISTURE_CS_PIN=${SOIL_MOISTURE_CS_PIN}
      - RELAY_PIN=${RELAY_PIN}

  nginx-api:
    image: "rpi-api:nginx"
    restart: unless-stopped

    command: sh -c "nginx -g 'daemon off;'"

    build: ./nginx

    networks:
      - api-nginx-net

    ports:
      - 5000:8000

    depends_on:
      api:
        condition: service_started

networks:
  api-nginx-net:
    driver: bridge