version: "3.9"

services:
  ######################################  
  webserver:
    image: "webserver:v1"
    restart: unless-stopped

    command: sh -c "./bin/server"

    # Debug tty connection
    #stdin_open: true
    #tty: true

    build:
      context: ./webserver

    depends_on:
      db:
        condition: service_healthy

    networks:
      - webserver-nginx-net
      - webserver-db-net

    environment:
      - DB_HOST=db
      - DB_USER=${APP_DB_USERNAME}
      - DB_PASS=${APP_DB_PASSWORD}
      - DB_NAME=${APP_DB_DBNAME}
      - DB_PORT=5432

  ######################################
  db:
    image: postgres:15.1
    restart: unless-stopped

    # Debug tty connection
    #stdin_open: true
    #tty: true
    
    networks:
      - webserver-db-net

    environment:
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD} 
      - POSTGRES_USER=${APP_DB_USERNAME}
      - POSTGRES_DB=${APP_DB_DBNAME} 

    # Comment out ports here if you do not want outside DB access
    ports:
      - ${APP_DB_OUT_PORT}:5432

    volumes:
      - ./db/data:/var/lib/postgresql/data/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_DB_USERNAME} -d ${APP_DB_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ######################################
  nginx-webserver:
    image: "webserver:nginx"
    restart: unless-stopped

    command: sh -c "nginx -g 'daemon off;'"

    build: ./nginx

    networks:
      - webserver-nginx-net

    ports:
      - ${NGINX_OUT_PORT}:8000

    depends_on:
      webserver:
        condition: service_started
      db:
        condition: service_healthy


##############################
networks:
  webserver-db-net:
    driver: bridge
  webserver-nginx-net:
    driver: bridge