version: "3.9"

services:
  webserver:
    image: "webserver:v1"
    restart: unless-stopped

    command: sh -c "./bin/server"

    # Debug tty connection
    #stdin_open: true
    #tty: true

    build:
      context: ./webserver

    depends_on:
      db:
        condition: service_started

    networks:
      - backend

    environment:
      - WEB_PORT=${APP_WEBSERVER_PORT}
      - DB_HOST=db
      - DB_USER=${APP_DB_USERNAME}
      - DB_PASS=${APP_DB_PASSWORD}
      - DB_NAME=${APP_DB_DBNAME}
      - DB_PORT=5432

  db:
    image: postgres:15.1
    restart: unless-stopped

    # Debug tty connection
    #stdin_open: true
    #tty: true
    
    networks:
      - backend

    environment:
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD} 
      - POSTGRES_USER=${APP_DB_USERNAME}
      - POSTGRES_DB=${APP_DB_DBNAME} 

    # Comment out ports here if you do not want outside DB access
    ports:
      - ${APP_DB_OUT_PORT}:5432

    volumes:
      - ./db/data:/var/lib/postgresql/data/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_DB_USERNAME} -d ${APP_DB_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge